# log_config.yaml

# 로깅 설정 파일
# 이 파일은 로깅 형식, 레벨, 파일 저장 경로 등을 정의하여 프로젝트의 모든 로그를 중앙에서 관리할 수 있도록 설정합니다.

version: 1
disable_existing_loggers: false

formatters:
    standard:
        format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
    detailed:
        format: '%(asctime)s [%(levelname)s] %(name)s:%(lineno)d: %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: standard
        stream: ext://sys.stdout

    file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: detailed
        filename: logs/trading_bot.log
        when: midnight
        interval: 1
        backupCount: 30
        encoding: utf8

    error_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: ERROR
        formatter: detailed
        filename: logs/error.log
        when: midnight
        interval: 1
        backupCount: 30
        encoding: utf8

root:
    level: DEBUG
    handlers: [console, file_handler, error_file_handler]
