# log_config.yaml

# 프로젝트 로깅 설정 파일
# 이 파일은 로깅 형식, 레벨, 파일 저장 경로 등을 정의하여 프로젝트의 모든 로그를 중앙에서 관리할 수 있도록 설정합니다.

version: 1
disable_existing_loggers: False

formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  simple:
    format: '%(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: detailed
    filename: logs/project.log

  error_handler:
    class: logging.FileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log

loggers:
  project_logger:
    level: DEBUG
    handlers: [console, file_handler, error_handler]
    propagate: False

root:
  level: DEBUG
  handlers: [console, file_handler]

---

# 사용법
# 로깅 설정을 적용하려면 다음과 같이 호출합니다:
# import logging
# import logging.config
# import yaml
#
# with open('log_config.yaml', 'r') as file:
#     config = yaml.safe_load(file)
# logging.config.dictConfig(config)
# logger = logging.getLogger('project_logger')
# logger.info("로깅 설정 완료")

---

# 파일 경로
# **경로**: 최상위 디렉터리(`/`)
